package com.github.technus.signalTester.plugin.mccUniversalLibrary.jna;

import com.sun.jna.*;
import com.sun.jna.ptr.*;
import com.sun.jna.win32.StdCallLibrary;

import java.io.File;
import java.nio.*;
/**
 * JNA Wrapper for library <b>mccUniversalLibrary</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class MccUniversalLibraryLibrary implements StdCallLibrary {
	public static void main(String[] args) {
		System.out.println("JNA_LIBRARY_NAME = " + JNA_LIBRARY_NAME);
	}

	public static final String JNA_LIBRARY_NAME = "cbw64.dll";
	static{
		//todo remove
		NativeLibrary.addSearchPath(JNA_LIBRARY_NAME,new File("C:\\Program Files (x86)\\Measurement Computing\\DAQ").getAbsolutePath());
	}
	public static final NativeLibrary JNA_NATIVE_LIB =NativeLibrary.getInstance(JNA_LIBRARY_NAME);
	static {
		Native.register(MccUniversalLibraryLibrary.class, MccUniversalLibraryLibrary.JNA_NATIVE_LIB);
	}
	
	public interface EVENTCALLBACK extends StdCallLibrary.StdCallCallback {
		void apply(int int1, int u1, int u2, Pointer voidPtr1);
	}

	/**
	 * Original signature : <code>int cbACalibrateData(int, long, int, USHORT*)</code><br>
	 * <i>native declaration : line 1559</i><br>
	 * @deprecated use the safer methods {@link #cbACalibrateData(int, com.sun.jna.NativeLong, int, java.nio.ShortBuffer)} and {@link #cbACalibrateData(int, com.sun.jna.NativeLong, int, com.sun.jna.ptr.ShortByReference)} instead
	 */
	@Deprecated 
	public static native int cbACalibrateData(int BoardNum, NativeLong NumPoints, int Gain, ShortByReference ADData);
	/**
	 * Original signature : <code>int cbACalibrateData(int, long, int, USHORT*)</code><br>
	 * <i>native declaration : line 1559</i>
	 */
	public static native int cbACalibrateData(int BoardNum, NativeLong NumPoints, int Gain, ShortBuffer ADData);
	/**
	 * Original signature : <code>int cbGetRevision(float*, float*)</code><br>
	 * <i>native declaration : line 1561</i><br>
	 * @deprecated use the safer methods {@link #cbGetRevision(java.nio.FloatBuffer, java.nio.FloatBuffer)} and {@link #cbGetRevision(com.sun.jna.ptr.FloatByReference, com.sun.jna.ptr.FloatByReference)} instead
	 */
	@Deprecated 
	public static native int cbGetRevision(FloatByReference RevNum, FloatByReference VxDRevNum);
	/**
	 * Original signature : <code>int cbGetRevision(float*, float*)</code><br>
	 * <i>native declaration : line 1561</i>
	 */
	public static native int cbGetRevision(FloatBuffer RevNum, FloatBuffer VxDRevNum);
	/**
	 * Original signature : <code>int cbLoadConfig(char*)</code><br>
	 * <i>native declaration : line 1562</i><br>
	 * @deprecated use the safer methods {@link #cbLoadConfig(java.lang.String)} and {@link #cbLoadConfig(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	public static native int cbLoadConfig(Pointer CfgFileName);
	/**
	 * Original signature : <code>int cbLoadConfig(char*)</code><br>
	 * <i>native declaration : line 1562</i>
	 */
	public static native int cbLoadConfig(String CfgFileName);
	/**
	 * Original signature : <code>int cbSaveConfig(char*)</code><br>
	 * <i>native declaration : line 1563</i><br>
	 * @deprecated use the safer methods {@link #cbSaveConfig(java.lang.String)} and {@link #cbSaveConfig(com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	public static native int cbSaveConfig(Pointer CfgFileName);
	/**
	 * Original signature : <code>int cbSaveConfig(char*)</code><br>
	 * <i>native declaration : line 1563</i>
	 */
	public static native int cbSaveConfig(String CfgFileName);
	/**
	 * Original signature : <code>int cbAConvertData(int, long, USHORT*, USHORT*)</code><br>
	 * <i>native declaration : line 1564</i><br>
	 * @deprecated use the safer methods {@link #cbAConvertData(int, com.sun.jna.NativeLong, java.nio.ShortBuffer, java.nio.ShortBuffer)} and {@link #cbAConvertData(int, com.sun.jna.NativeLong, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.ShortByReference)} instead
	 */
	@Deprecated 
	public static native int cbAConvertData(int BoardNum, NativeLong NumPoints, ShortByReference ADData, ShortByReference ChanTags);
	/**
	 * Original signature : <code>int cbAConvertData(int, long, USHORT*, USHORT*)</code><br>
	 * <i>native declaration : line 1564</i>
	 */
	public static native int cbAConvertData(int BoardNum, NativeLong NumPoints, ShortBuffer ADData, ShortBuffer ChanTags);
	/**
	 * Original signature : <code>int cbAConvertPretrigData(int, long, long, USHORT*, USHORT*)</code><br>
	 * <i>native declaration : line 1566</i><br>
	 * @deprecated use the safer methods {@link #cbAConvertPretrigData(int, com.sun.jna.NativeLong, com.sun.jna.NativeLong, java.nio.ShortBuffer, java.nio.ShortBuffer)} and {@link #cbAConvertPretrigData(int, com.sun.jna.NativeLong, com.sun.jna.NativeLong, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.ShortByReference)} instead
	 */
	@Deprecated 
	public static native int cbAConvertPretrigData(int BoardNum, NativeLong PreTrigCount, NativeLong TotalCount, ShortByReference ADData, ShortByReference ChanTags);
	/**
	 * Original signature : <code>int cbAConvertPretrigData(int, long, long, USHORT*, USHORT*)</code><br>
	 * <i>native declaration : line 1566</i>
	 */
	public static native int cbAConvertPretrigData(int BoardNum, NativeLong PreTrigCount, NativeLong TotalCount, ShortBuffer ADData, ShortBuffer ChanTags);
	/**
	 * Original signature : <code>int cbAIn(int, int, int, USHORT*)</code><br>
	 * <i>native declaration : line 1569</i><br>
	 * @deprecated use the safer methods {@link #cbAIn(int, int, int, java.nio.ShortBuffer)} and {@link #cbAIn(int, int, int, com.sun.jna.ptr.ShortByReference)} instead
	 */
	@Deprecated 
	public static native int cbAIn(int BoardNum, int Chan, int Gain, ShortByReference DataValue);
	/**
	 * Original signature : <code>int cbAIn(int, int, int, USHORT*)</code><br>
	 * <i>native declaration : line 1569</i>
	 */
	public static native int cbAIn(int BoardNum, int Chan, int Gain, ShortBuffer DataValue);
	/**
	 * Original signature : <code>int cbAIn32(int, int, int, ULONG*, int)</code><br>
	 * <i>native declaration : line 1570</i>
	 */
	public static native int cbAIn32(int BoardNum, int Chan, int Gain, NativeLongByReference DataValue, int Options);
	/**
	 * Original signature : <code>int cbAInScan(int, int, int, long, long*, int, HGLOBAL, int)</code><br>
	 * <i>native declaration : line 1571</i>
	 */
	public static native int cbAInScan(int BoardNum, int LowChan, int HighChan, NativeLong Count, NativeLongByReference Rate, int Gain, MccUniversalLibraryLibrary.HGLOBAL MemHandle, int Options);
	/**
	 * Original signature : <code>int cbALoadQueue(int, short*, short*, int)</code><br>
	 * <i>native declaration : line 1574</i><br>
	 * @deprecated use the safer methods {@link #cbALoadQueue(int, java.nio.ShortBuffer, java.nio.ShortBuffer, int)} and {@link #cbALoadQueue(int, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.ShortByReference, int)} instead
	 */
	@Deprecated 
	public static native int cbALoadQueue(int BoardNum, ShortByReference ChanArray, ShortByReference GainArray, int NumChans);
	/**
	 * Original signature : <code>int cbALoadQueue(int, short*, short*, int)</code><br>
	 * <i>native declaration : line 1574</i>
	 */
	public static native int cbALoadQueue(int BoardNum, ShortBuffer ChanArray, ShortBuffer GainArray, int NumChans);
	/**
	 * Original signature : <code>int cbAOut(int, int, int, USHORT)</code><br>
	 * <i>native declaration : line 1576</i>
	 */
	public static native int cbAOut(int BoardNum, int Chan, int Gain, short DataValue);
	/**
	 * Original signature : <code>int cbAOutScan(int, int, int, long, long*, int, HGLOBAL, int)</code><br>
	 * <i>native declaration : line 1577</i>
	 */
	public static native int cbAOutScan(int BoardNum, int LowChan, int HighChan, NativeLong Count, NativeLongByReference Rate, int Gain, MccUniversalLibraryLibrary.HGLOBAL MemHandle, int Options);
	/**
	 * Original signature : <code>int cbAPretrig(int, int, int, long*, long*, long*, int, HGLOBAL, int)</code><br>
	 * <i>native declaration : line 1580</i>
	 */
	public static native int cbAPretrig(int BoardNum, int LowChan, int HighChan, NativeLongByReference PreTrigCount, NativeLongByReference TotalCount, NativeLongByReference Rate, int Gain, MccUniversalLibraryLibrary.HGLOBAL MemHandle, int Options);
	/**
	 * Original signature : <code>int cbATrig(int, int, int, USHORT, int, USHORT*)</code><br>
	 * <i>native declaration : line 1583</i><br>
	 * @deprecated use the safer methods {@link #cbATrig(int, int, int, short, int, java.nio.ShortBuffer)} and {@link #cbATrig(int, int, int, short, int, com.sun.jna.ptr.ShortByReference)} instead
	 */
	@Deprecated 
	public static native int cbATrig(int BoardNum, int Chan, int TrigType, short TrigValue, int Gain, ShortByReference DataValue);
	/**
	 * Original signature : <code>int cbATrig(int, int, int, USHORT, int, USHORT*)</code><br>
	 * <i>native declaration : line 1583</i>
	 */
	public static native int cbATrig(int BoardNum, int Chan, int TrigType, short TrigValue, int Gain, ShortBuffer DataValue);
	/**
	 * Original signature : <code>int cbC7266Config(int, int, int, int, int, int, int, int, int)</code><br>
	 * <i>native declaration : line 1585</i>
	 */
	public static native int cbC7266Config(int BoardNum, int CounterNum, int Quadrature, int CountingMode, int DataEncoding, int IndexMode, int InvertIndex, int FlagPins, int GateEnable);
	/**
	 * Original signature : <code>int cbC8254Config(int, int, int)</code><br>
	 * <i>native declaration : line 1588</i>
	 */
	public static native int cbC8254Config(int BoardNum, int CounterNum, int Config);
	/**
	 * Original signature : <code>int cbC8536Config(int, int, int, int, int)</code><br>
	 * <i>native declaration : line 1589</i>
	 */
	public static native int cbC8536Config(int BoardNum, int CounterNum, int OutputControl, int RecycleMode, int TrigType);
	/**
	 * Original signature : <code>int cbC9513Config(int, int, int, int, int, int, int, int, int, int, int)</code><br>
	 * <i>native declaration : line 1591</i>
	 */
	public static native int cbC9513Config(int BoardNum, int CounterNum, int GateControl, int CounterEdge, int CountSource, int SpecialGate, int Reload, int RecycleMode, int BCDMode, int CountDirection, int OutputControl);
	/**
	 * Original signature : <code>int cbC8536Init(int, int, int)</code><br>
	 * <i>native declaration : line 1596</i>
	 */
	public static native int cbC8536Init(int BoardNum, int ChipNum, int Ctr1Output);
	/**
	 * Original signature : <code>int cbC9513Init(int, int, int, int, int, int, int)</code><br>
	 * <i>native declaration : line 1597</i>
	 */
	public static native int cbC9513Init(int BoardNum, int ChipNum, int FOutDivider, int FOutSource, int Compare1, int Compare2, int TimeOfDay);
	/**
	 * Original signature : <code>int cbCFreqIn(int, int, int, USHORT*, long*)</code><br>
	 * <i>native declaration : line 1600</i><br>
	 * @deprecated use the safer methods {@link #cbCFreqIn(int, int, int, java.nio.ShortBuffer, com.sun.jna.ptr.NativeLongByReference)} and {@link #cbCFreqIn(int, int, int, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.NativeLongByReference)} instead
	 */
	@Deprecated 
	public static native int cbCFreqIn(int BoardNum, int SigSource, int GateInterval, ShortByReference Count, NativeLongByReference Freq);
	/**
	 * Original signature : <code>int cbCFreqIn(int, int, int, USHORT*, long*)</code><br>
	 * <i>native declaration : line 1600</i>
	 */
	public static native int cbCFreqIn(int BoardNum, int SigSource, int GateInterval, ShortBuffer Count, NativeLongByReference Freq);
	/**
	 * Original signature : <code>int cbCIn(int, int, USHORT*)</code><br>
	 * <i>native declaration : line 1602</i><br>
	 * @deprecated use the safer methods {@link #cbCIn(int, int, java.nio.ShortBuffer)} and {@link #cbCIn(int, int, com.sun.jna.ptr.ShortByReference)} instead
	 */
	@Deprecated 
	public static native int cbCIn(int BoardNum, int CounterNum, ShortByReference Count);
	/**
	 * Original signature : <code>int cbCIn(int, int, USHORT*)</code><br>
	 * <i>native declaration : line 1602</i>
	 */
	public static native int cbCIn(int BoardNum, int CounterNum, ShortBuffer Count);
	/**
	 * Original signature : <code>int cbCIn32(int, int, ULONG*)</code><br>
	 * <i>native declaration : line 1603</i>
	 */
	public static native int cbCIn32(int BoardNum, int CounterNum, NativeLongByReference Count);
	/**
	 * Original signature : <code>int cbCIn64(int, int, ULONGLONG*)</code><br>
	 * <i>native declaration : line 1604</i><br>
	 * @deprecated use the safer methods {@link #cbCIn64(int, int, java.nio.LongBuffer)} and {@link #cbCIn64(int, int, com.sun.jna.ptr.LongByReference)} instead
	 */
	@Deprecated 
	public static native int cbCIn64(int BoardNum, int CounterNum, LongByReference Count);
	/**
	 * Original signature : <code>int cbCIn64(int, int, ULONGLONG*)</code><br>
	 * <i>native declaration : line 1604</i>
	 */
	public static native int cbCIn64(int BoardNum, int CounterNum, LongBuffer Count);
	/**
	 * Original signature : <code>int cbCLoad(int, int, unsigned int)</code><br>
	 * <i>native declaration : line 1605</i>
	 */
	public static native int cbCLoad(int BoardNum, int RegNum, int LoadValue);
	/**
	 * Original signature : <code>int cbCLoad32(int, int, ULONG)</code><br>
	 * <i>native declaration : line 1606</i>
	 */
	public static native int cbCLoad32(int BoardNum, int RegNum, NativeLong LoadValue);
	/**
	 * Original signature : <code>int cbCLoad64(int, int, ULONGLONG)</code><br>
	 * <i>native declaration : line 1607</i>
	 */
	public static native int cbCLoad64(int BoardNum, int RegNum, long LoadValue);
	/**
	 * Original signature : <code>int cbCStatus(int, int, ULONG*)</code><br>
	 * <i>native declaration : line 1608</i>
	 */
	public static native int cbCStatus(int BoardNum, int CounterNum, NativeLongByReference StatusBits);
	/**
	 * Original signature : <code>int cbCStoreOnInt(int, int, short*, HGLOBAL)</code><br>
	 * <i>native declaration : line 1609</i><br>
	 * @deprecated use the safer methods {@link #cbCStoreOnInt(int, int, java.nio.ShortBuffer, mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL)} and {@link #cbCStoreOnInt(int, int, com.sun.jna.ptr.ShortByReference, mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL)} instead
	 */
	@Deprecated 
	public static native int cbCStoreOnInt(int BoardNum, int IntCount, ShortByReference CntrControl, MccUniversalLibraryLibrary.HGLOBAL MemHandle);
	/**
	 * Original signature : <code>int cbCStoreOnInt(int, int, short*, HGLOBAL)</code><br>
	 * <i>native declaration : line 1609</i>
	 */
	public static native int cbCStoreOnInt(int BoardNum, int IntCount, ShortBuffer CntrControl, MccUniversalLibraryLibrary.HGLOBAL MemHandle);
	/**
	 * Original signature : <code>int cbCInScan(int, int, int, LONG, LONG*, HGLOBAL, ULONG)</code><br>
	 * <i>native declaration : line 1611</i>
	 */
	public static native int cbCInScan(int BoardNum, int FirstCtr, int LastCtr, NativeLong Count, NativeLongByReference Rate, MccUniversalLibraryLibrary.HGLOBAL MemHandle, NativeLong Options);
	/**
	 * Original signature : <code>int cbCConfigScan(int, int, int, int, int, int, int, int)</code><br>
	 * <i>native declaration : line 1613</i>
	 */
	public static native int cbCConfigScan(int BoardNum, int CounterNum, int Mode, int DebounceTime, int DebounceMode, int EdgeDetection, int TickSize, int MappedChannel);
	/**
	 * Original signature : <code>int cbCClear(int, int)</code><br>
	 * <i>native declaration : line 1616</i>
	 */
	public static native int cbCClear(int BoardNum, int CounterNum);
	/**
	 * Original signature : <code>int cbTimerOutStart(int, int, double*)</code><br>
	 * <i>native declaration : line 1617</i><br>
	 * @deprecated use the safer methods {@link #cbTimerOutStart(int, int, java.nio.DoubleBuffer)} and {@link #cbTimerOutStart(int, int, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Deprecated 
	public static native int cbTimerOutStart(int BoardNum, int TimerNum, DoubleByReference Frequency);
	/**
	 * Original signature : <code>int cbTimerOutStart(int, int, double*)</code><br>
	 * <i>native declaration : line 1617</i>
	 */
	public static native int cbTimerOutStart(int BoardNum, int TimerNum, DoubleBuffer Frequency);
	/**
	 * Original signature : <code>int cbTimerOutStop(int, int)</code><br>
	 * <i>native declaration : line 1618</i>
	 */
	public static native int cbTimerOutStop(int BoardNum, int TimerNum);
	/**
	 * Original signature : <code>int cbPulseOutStart(int, int, double*, double*, unsigned int, double*, int, int)</code><br>
	 * <i>native declaration : line 1619</i><br>
	 * @deprecated use the safer methods {@link #cbPulseOutStart(int, int, java.nio.DoubleBuffer, java.nio.DoubleBuffer, int, java.nio.DoubleBuffer, int, int)} and {@link #cbPulseOutStart(int, int, com.sun.jna.ptr.DoubleByReference, com.sun.jna.ptr.DoubleByReference, int, com.sun.jna.ptr.DoubleByReference, int, int)} instead
	 */
	@Deprecated 
	public static native int cbPulseOutStart(int BoardNum, int TimerNum, DoubleByReference Frequency, DoubleByReference DutyCycle, int PulseCount, DoubleByReference InitialDelay, int IdleState, int Options);
	/**
	 * Original signature : <code>int cbPulseOutStart(int, int, double*, double*, unsigned int, double*, int, int)</code><br>
	 * <i>native declaration : line 1619</i>
	 */
	public static native int cbPulseOutStart(int BoardNum, int TimerNum, DoubleBuffer Frequency, DoubleBuffer DutyCycle, int PulseCount, DoubleBuffer InitialDelay, int IdleState, int Options);
	/**
	 * Original signature : <code>int cbPulseOutStop(int, int)</code><br>
	 * <i>native declaration : line 1620</i>
	 */
	public static native int cbPulseOutStop(int BoardNum, int TimerNum);
	/**
	 * Original signature : <code>int cbDBitIn(int, int, int, USHORT*)</code><br>
	 * <i>native declaration : line 1621</i><br>
	 * @deprecated use the safer methods {@link #cbDBitIn(int, int, int, java.nio.ShortBuffer)} and {@link #cbDBitIn(int, int, int, com.sun.jna.ptr.ShortByReference)} instead
	 */
	@Deprecated 
	public static native int cbDBitIn(int BoardNum, int PortType, int BitNum, ShortByReference BitValue);
	/**
	 * Original signature : <code>int cbDBitIn(int, int, int, USHORT*)</code><br>
	 * <i>native declaration : line 1621</i>
	 */
	public static native int cbDBitIn(int BoardNum, int PortType, int BitNum, ShortBuffer BitValue);
	/**
	 * Original signature : <code>int cbDBitOut(int, int, int, USHORT)</code><br>
	 * <i>native declaration : line 1623</i>
	 */
	public static native int cbDBitOut(int BoardNum, int PortType, int BitNum, short BitValue);
	/**
	 * Original signature : <code>int cbDConfigPort(int, int, int)</code><br>
	 * <i>native declaration : line 1624</i>
	 */
	public static native int cbDConfigPort(int BoardNum, int PortType, int Direction);
	/**
	 * Original signature : <code>int cbDConfigBit(int, int, int, int)</code><br>
	 * <i>native declaration : line 1625</i>
	 */
	public static native int cbDConfigBit(int BoardNum, int PortType, int BitNum, int Direction);
	/**
	 * Original signature : <code>int cbDIn(int, int, USHORT*)</code><br>
	 * <i>native declaration : line 1626</i><br>
	 * @deprecated use the safer methods {@link #cbDIn(int, int, java.nio.ShortBuffer)} and {@link #cbDIn(int, int, com.sun.jna.ptr.ShortByReference)} instead
	 */
	@Deprecated 
	public static native int cbDIn(int BoardNum, int PortType, ShortByReference DataValue);
	/**
	 * Original signature : <code>int cbDIn(int, int, USHORT*)</code><br>
	 * <i>native declaration : line 1626</i>
	 */
	public static native int cbDIn(int BoardNum, int PortType, ShortBuffer DataValue);
	/**
	 * Original signature : <code>int cbDIn32(int, int, UINT*)</code><br>
	 * <i>native declaration : line 1627</i><br>
	 * @deprecated use the safer methods {@link #cbDIn32(int, int, java.nio.IntBuffer)} and {@link #cbDIn32(int, int, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbDIn32(int BoardNum, int PortType, IntByReference DataValue);
	/**
	 * Original signature : <code>int cbDIn32(int, int, UINT*)</code><br>
	 * <i>native declaration : line 1627</i>
	 */
	public static native int cbDIn32(int BoardNum, int PortType, IntBuffer DataValue);
	/**
	 * Original signature : <code>int cbDInScan(int, int, long, long*, HGLOBAL, int)</code><br>
	 * <i>native declaration : line 1628</i>
	 */
	public static native int cbDInScan(int BoardNum, int PortType, NativeLong Count, NativeLongByReference Rate, MccUniversalLibraryLibrary.HGLOBAL MemHandle, int Options);
	/**
	 * Original signature : <code>int cbDOut(int, int, USHORT)</code><br>
	 * <i>native declaration : line 1630</i>
	 */
	public static native int cbDOut(int BoardNum, int PortType, short DataValue);
	/**
	 * Original signature : <code>int cbDOut32(int, int, UINT)</code><br>
	 * <i>native declaration : line 1631</i>
	 */
	public static native int cbDOut32(int BoardNum, int PortType, int DataValue);
	/**
	 * Original signature : <code>int cbDOutScan(int, int, long, long*, HGLOBAL, int)</code><br>
	 * <i>native declaration : line 1632</i>
	 */
	public static native int cbDOutScan(int BoardNum, int PortType, NativeLong Count, NativeLongByReference Rate, MccUniversalLibraryLibrary.HGLOBAL MemHandle, int Options);
	/**
	 * Original signature : <code>int cbDInArray(int, int, int, ULONG*)</code><br>
	 * <i>native declaration : line 1634</i>
	 */
	public static native int cbDInArray(int BoardNum, int LowPort, int HighPort, NativeLongByReference DataArray);
	/**
	 * Original signature : <code>int cbDOutArray(int, int, int, ULONG*)</code><br>
	 * <i>native declaration : line 1635</i>
	 */
	public static native int cbDOutArray(int BoardNum, int LowPort, int HighPort, NativeLongByReference DataArray);
	/**
	 * Original signature : <code>int cbDClearAlarm(int, int, UINT)</code><br>
	 * <i>native declaration : line 1636</i>
	 */
	public static native int cbDClearAlarm(int BoardNum, int PortType, int Mask);
	/**
	 * Original signature : <code>int cbErrHandling(int, int)</code><br>
	 * <i>native declaration : line 1637</i>
	 */
	public static native int cbErrHandling(int ErrReporting, int ErrHandling);
	/**
	 * Original signature : <code>int cbFileAInScan(int, int, int, long, long*, int, char*, int)</code><br>
	 * <i>native declaration : line 1638</i><br>
	 * @deprecated use the safer methods {@link #cbFileAInScan(int, int, int, com.sun.jna.NativeLong, com.sun.jna.ptr.NativeLongByReference, int, java.lang.String, int)} and {@link #cbFileAInScan(int, int, int, com.sun.jna.NativeLong, com.sun.jna.ptr.NativeLongByReference, int, com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	public static native int cbFileAInScan(int BoardNum, int LowChan, int HighChan, NativeLong Count, NativeLongByReference Rate, int Gain, Pointer FileName, int Options);
	/**
	 * Original signature : <code>int cbFileAInScan(int, int, int, long, long*, int, char*, int)</code><br>
	 * <i>native declaration : line 1638</i>
	 */
	public static native int cbFileAInScan(int BoardNum, int LowChan, int HighChan, NativeLong Count, NativeLongByReference Rate, int Gain, String FileName, int Options);
	/**
	 * Original signature : <code>int cbFileGetInfo(char*, short*, short*, long*, long*, long*, int*)</code><br>
	 * <i>native declaration : line 1641</i><br>
	 * @deprecated use the safer methods {@link #cbFileGetInfo(java.lang.String, java.nio.ShortBuffer, java.nio.ShortBuffer, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.NativeLongByReference, java.nio.IntBuffer)} and {@link #cbFileGetInfo(com.sun.jna.Pointer, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbFileGetInfo(Pointer FileName, ShortByReference LowChan, ShortByReference HighChan, NativeLongByReference PreTrigCount, NativeLongByReference TotalCount, NativeLongByReference Rate, IntByReference Gain);
	/**
	 * Original signature : <code>int cbFileGetInfo(char*, short*, short*, long*, long*, long*, int*)</code><br>
	 * <i>native declaration : line 1641</i>
	 */
	public static native int cbFileGetInfo(String FileName, ShortBuffer LowChan, ShortBuffer HighChan, NativeLongByReference PreTrigCount, NativeLongByReference TotalCount, NativeLongByReference Rate, IntBuffer Gain);
	/**
	 * Original signature : <code>int cbFilePretrig(int, int, int, long*, long*, long*, int, char*, int)</code><br>
	 * <i>native declaration : line 1644</i><br>
	 * @deprecated use the safer methods {@link #cbFilePretrig(int, int, int, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.NativeLongByReference, int, java.lang.String, int)} and {@link #cbFilePretrig(int, int, int, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.NativeLongByReference, int, com.sun.jna.Pointer, int)} instead
	 */
	@Deprecated 
	public static native int cbFilePretrig(int BoardNum, int LowChan, int HighChan, NativeLongByReference PreTrigCount, NativeLongByReference TotalCount, NativeLongByReference Rate, int Gain, Pointer FileName, int Options);
	/**
	 * Original signature : <code>int cbFilePretrig(int, int, int, long*, long*, long*, int, char*, int)</code><br>
	 * <i>native declaration : line 1644</i>
	 */
	public static native int cbFilePretrig(int BoardNum, int LowChan, int HighChan, NativeLongByReference PreTrigCount, NativeLongByReference TotalCount, NativeLongByReference Rate, int Gain, String FileName, int Options);
	/**
	 * Original signature : <code>int cbFileRead(char*, long, long*, USHORT*)</code><br>
	 * <i>native declaration : line 1648</i><br>
	 * @deprecated use the safer methods {@link #cbFileRead(java.lang.String, com.sun.jna.NativeLong, com.sun.jna.ptr.NativeLongByReference, java.nio.ShortBuffer)} and {@link #cbFileRead(com.sun.jna.Pointer, com.sun.jna.NativeLong, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.ShortByReference)} instead
	 */
	@Deprecated 
	public static native int cbFileRead(Pointer FileName, NativeLong FirstPoint, NativeLongByReference NumPoints, ShortByReference DataBuffer);
	/**
	 * Original signature : <code>int cbFileRead(char*, long, long*, USHORT*)</code><br>
	 * <i>native declaration : line 1648</i>
	 */
	public static native int cbFileRead(String FileName, NativeLong FirstPoint, NativeLongByReference NumPoints, ShortBuffer DataBuffer);
	/**
	 * Original signature : <code>int cbFlashLED(int)</code><br>
	 * <i>native declaration : line 1650</i>
	 */
	public static native int cbFlashLED(int BoardNum);
	/**
	 * Original signature : <code>int cbGetErrMsg(int, char*)</code><br>
	 * <i>native declaration : line 1651</i><br>
	 * @deprecated use the safer methods {@link #cbGetErrMsg(int, java.lang.String)} and {@link #cbGetErrMsg(int, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	public static native int cbGetErrMsg(int ErrCode, Pointer ErrMsg);
	/**
	 * Original signature : <code>int cbGetErrMsg(int, char*)</code><br>
	 * <i>native declaration : line 1651</i>
	 */
	public static native int cbGetErrMsg(int ErrCode, String ErrMsg);
	/**
	 * Original signature : <code>int cbGetIOStatus(int, short*, long*, long*, int)</code><br>
	 * <i>native declaration : line 1652</i><br>
	 * @deprecated use the safer methods {@link #cbGetIOStatus(int, java.nio.ShortBuffer, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.NativeLongByReference, int)} and {@link #cbGetIOStatus(int, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.NativeLongByReference, int)} instead
	 */
	@Deprecated 
	public static native int cbGetIOStatus(int BoardNum, ShortByReference Status, NativeLongByReference CurCount, NativeLongByReference CurIndex, int FunctionType);
	/**
	 * Original signature : <code>int cbGetIOStatus(int, short*, long*, long*, int)</code><br>
	 * <i>native declaration : line 1652</i>
	 */
	public static native int cbGetIOStatus(int BoardNum, ShortBuffer Status, NativeLongByReference CurCount, NativeLongByReference CurIndex, int FunctionType);
	/**
	 * Original signature : <code>int cbRS485(int, int, int)</code><br>
	 * <i>native declaration : line 1654</i>
	 */
	public static native int cbRS485(int BoardNum, int Transmit, int Receive);
	/**
	 * Original signature : <code>int cbStopIOBackground(int, int)</code><br>
	 * <i>native declaration : line 1655</i>
	 */
	public static native int cbStopIOBackground(int BoardNum, int FunctionType);
	/**
	 * Original signature : <code>int cbTIn(int, int, int, float*, int)</code><br>
	 * <i>native declaration : line 1656</i><br>
	 * @deprecated use the safer methods {@link #cbTIn(int, int, int, java.nio.FloatBuffer, int)} and {@link #cbTIn(int, int, int, com.sun.jna.ptr.FloatByReference, int)} instead
	 */
	@Deprecated 
	public static native int cbTIn(int BoardNum, int Chan, int Scale, FloatByReference TempValue, int Options);
	/**
	 * Original signature : <code>int cbTIn(int, int, int, float*, int)</code><br>
	 * <i>native declaration : line 1656</i>
	 */
	public static native int cbTIn(int BoardNum, int Chan, int Scale, FloatBuffer TempValue, int Options);
	/**
	 * Original signature : <code>int cbTInScan(int, int, int, int, float*, int)</code><br>
	 * <i>native declaration : line 1658</i><br>
	 * @deprecated use the safer methods {@link #cbTInScan(int, int, int, int, java.nio.FloatBuffer, int)} and {@link #cbTInScan(int, int, int, int, com.sun.jna.ptr.FloatByReference, int)} instead
	 */
	@Deprecated 
	public static native int cbTInScan(int BoardNum, int LowChan, int HighChan, int Scale, FloatByReference DataBuffer, int Options);
	/**
	 * Original signature : <code>int cbTInScan(int, int, int, int, float*, int)</code><br>
	 * <i>native declaration : line 1658</i>
	 */
	public static native int cbTInScan(int BoardNum, int LowChan, int HighChan, int Scale, FloatBuffer DataBuffer, int Options);

	///**todo most likely deprecated???
	// * Original signature : <code>int cbMemSetDTMode(int, int)</code><br>
	// * <i>native declaration : line 1660</i>
	// */
	//public static native int cbMemSetDTMode(int BoardNum, int Mode);

	/**
	 * Original signature : <code>int cbMemReset(int)</code><br>
	 * <i>native declaration : line 1661</i>
	 */
	public static native int cbMemReset(int BoardNum);
	/**
	 * Original signature : <code>int cbMemRead(int, USHORT*, long, long)</code><br>
	 * <i>native declaration : line 1662</i><br>
	 * @deprecated use the safer methods {@link #cbMemRead(int, java.nio.ShortBuffer, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} and {@link #cbMemRead(int, com.sun.jna.ptr.ShortByReference, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} instead
	 */
	@Deprecated 
	public static native int cbMemRead(int BoardNum, ShortByReference DataBuffer, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbMemRead(int, USHORT*, long, long)</code><br>
	 * <i>native declaration : line 1662</i>
	 */
	public static native int cbMemRead(int BoardNum, ShortBuffer DataBuffer, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbMemWrite(int, USHORT*, long, long)</code><br>
	 * <i>native declaration : line 1664</i><br>
	 * @deprecated use the safer methods {@link #cbMemWrite(int, java.nio.ShortBuffer, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} and {@link #cbMemWrite(int, com.sun.jna.ptr.ShortByReference, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} instead
	 */
	@Deprecated 
	public static native int cbMemWrite(int BoardNum, ShortByReference DataBuffer, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbMemWrite(int, USHORT*, long, long)</code><br>
	 * <i>native declaration : line 1664</i>
	 */
	public static native int cbMemWrite(int BoardNum, ShortBuffer DataBuffer, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbMemReadPretrig(int, USHORT*, long, long)</code><br>
	 * <i>native declaration : line 1666</i><br>
	 * @deprecated use the safer methods {@link #cbMemReadPretrig(int, java.nio.ShortBuffer, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} and {@link #cbMemReadPretrig(int, com.sun.jna.ptr.ShortByReference, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} instead
	 */
	@Deprecated 
	public static native int cbMemReadPretrig(int BoardNum, ShortByReference DataBuffer, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbMemReadPretrig(int, USHORT*, long, long)</code><br>
	 * <i>native declaration : line 1666</i>
	 */
	public static native int cbMemReadPretrig(int BoardNum, ShortBuffer DataBuffer, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbWinBufToArray(HGLOBAL, USHORT*, long, long)</code><br>
	 * <i>native declaration : line 1668</i><br>
	 * @deprecated use the safer methods {@link #cbWinBufToArray(mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, java.nio.ShortBuffer, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} and {@link #cbWinBufToArray(mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, com.sun.jna.ptr.ShortByReference, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} instead
	 */
	@Deprecated 
	public static native int cbWinBufToArray(MccUniversalLibraryLibrary.HGLOBAL MemHandle, ShortByReference DataArray, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbWinBufToArray(HGLOBAL, USHORT*, long, long)</code><br>
	 * <i>native declaration : line 1668</i>
	 */
	public static native int cbWinBufToArray(MccUniversalLibraryLibrary.HGLOBAL MemHandle, ShortBuffer DataArray, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbWinBufToArray32(HGLOBAL, ULONG*, long, long)</code><br>
	 * <i>native declaration : line 1670</i>
	 */
	public static native int cbWinBufToArray32(MccUniversalLibraryLibrary.HGLOBAL MemHandle, NativeLongByReference DataArray, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbWinBufToArray64(HGLOBAL, ULONGLONG*, long, long)</code><br>
	 * <i>native declaration : line 1673</i><br>
	 * @deprecated use the safer methods {@link #cbWinBufToArray64(mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, java.nio.LongBuffer, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} and {@link #cbWinBufToArray64(mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, com.sun.jna.ptr.LongByReference, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} instead
	 */
	@Deprecated 
	public static native int cbWinBufToArray64(MccUniversalLibraryLibrary.HGLOBAL MemHandle, LongByReference DataArray, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbWinBufToArray64(HGLOBAL, ULONGLONG*, long, long)</code><br>
	 * <i>native declaration : line 1673</i>
	 */
	public static native int cbWinBufToArray64(MccUniversalLibraryLibrary.HGLOBAL MemHandle, LongBuffer DataArray, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>HGLOBAL cbScaledWinBufAlloc(long)</code><br>
	 * <i>native declaration : line 1676</i>
	 */
	public static native MccUniversalLibraryLibrary.HGLOBAL cbScaledWinBufAlloc(NativeLong NumPoints);
	/**
	 * Original signature : <code>int cbScaledWinBufToArray(HGLOBAL, double*, long, long)</code><br>
	 * <i>native declaration : line 1677</i><br>
	 * @deprecated use the safer methods {@link #cbScaledWinBufToArray(mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, java.nio.DoubleBuffer, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} and {@link #cbScaledWinBufToArray(mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, com.sun.jna.ptr.DoubleByReference, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} instead
	 */
	@Deprecated 
	public static native int cbScaledWinBufToArray(MccUniversalLibraryLibrary.HGLOBAL MemHandle, DoubleByReference DataArray, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbScaledWinBufToArray(HGLOBAL, double*, long, long)</code><br>
	 * <i>native declaration : line 1677</i>
	 */
	public static native int cbScaledWinBufToArray(MccUniversalLibraryLibrary.HGLOBAL MemHandle, DoubleBuffer DataArray, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbWinArrayToBuf(USHORT*, HGLOBAL, long, long)</code><br>
	 * <i>native declaration : line 1680</i><br>
	 * @deprecated use the safer methods {@link #cbWinArrayToBuf(java.nio.ShortBuffer, mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} and {@link #cbWinArrayToBuf(com.sun.jna.ptr.ShortByReference, mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} instead
	 */
	@Deprecated 
	public static native int cbWinArrayToBuf(ShortByReference DataArray, MccUniversalLibraryLibrary.HGLOBAL MemHandle, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbWinArrayToBuf(USHORT*, HGLOBAL, long, long)</code><br>
	 * <i>native declaration : line 1680</i>
	 */
	public static native int cbWinArrayToBuf(ShortBuffer DataArray, MccUniversalLibraryLibrary.HGLOBAL MemHandle, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbWinArrayToBuf32(ULONG*, HGLOBAL, long, long)</code><br>
	 * <i>native declaration : line 1682</i>
	 */
	public static native int cbWinArrayToBuf32(NativeLongByReference DataArray, MccUniversalLibraryLibrary.HGLOBAL MemHandle, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbScaledWinArrayToBuf(double*, HGLOBAL, long, long)</code><br>
	 * <i>native declaration : line 1684</i><br>
	 * @deprecated use the safer methods {@link #cbScaledWinArrayToBuf(java.nio.DoubleBuffer, mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} and {@link #cbScaledWinArrayToBuf(com.sun.jna.ptr.DoubleByReference, mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, com.sun.jna.NativeLong, com.sun.jna.NativeLong)} instead
	 */
	@Deprecated 
	public static native int cbScaledWinArrayToBuf(DoubleByReference DataArray, MccUniversalLibraryLibrary.HGLOBAL MemHandle, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>int cbScaledWinArrayToBuf(double*, HGLOBAL, long, long)</code><br>
	 * <i>native declaration : line 1684</i>
	 */
	public static native int cbScaledWinArrayToBuf(DoubleBuffer DataArray, MccUniversalLibraryLibrary.HGLOBAL MemHandle, NativeLong FirstPoint, NativeLong Count);
	/**
	 * Original signature : <code>HGLOBAL cbWinBufAlloc(long)</code><br>
	 * <i>native declaration : line 1687</i>
	 */
	public static native MccUniversalLibraryLibrary.HGLOBAL cbWinBufAlloc(NativeLong NumPoints);
	/**
	 * Original signature : <code>HGLOBAL cbWinBufAlloc32(long)</code><br>
	 * <i>native declaration : line 1688</i>
	 */
	public static native MccUniversalLibraryLibrary.HGLOBAL cbWinBufAlloc32(NativeLong NumPoints);
	/**
	 * Original signature : <code>HGLOBAL cbWinBufAlloc64(long)</code><br>
	 * <i>native declaration : line 1689</i>
	 */
	public static native MccUniversalLibraryLibrary.HGLOBAL cbWinBufAlloc64(NativeLong NumPoints);
	/**
	 * Original signature : <code>int cbWinBufFree(HGLOBAL)</code><br>
	 * <i>native declaration : line 1690</i>
	 */
	public static native int cbWinBufFree(MccUniversalLibraryLibrary.HGLOBAL MemHandle);
	/**
	 * Original signature : <code>int cbInByte(int, int)</code><br>
	 * <i>native declaration : line 1691</i>
	 */
	public static native int cbInByte(int BoardNum, int PortNum);
	/**
	 * Original signature : <code>int cbOutByte(int, int, int)</code><br>
	 * <i>native declaration : line 1692</i>
	 */
	public static native int cbOutByte(int BoardNum, int PortNum, int PortVal);
	/**
	 * Original signature : <code>int cbInWord(int, int)</code><br>
	 * <i>native declaration : line 1693</i>
	 */
	public static native int cbInWord(int BoardNum, int PortNum);
	/**
	 * Original signature : <code>int cbOutWord(int, int, int)</code><br>
	 * <i>native declaration : line 1694</i>
	 */
	public static native int cbOutWord(int BoardNum, int PortNum, int PortVal);
	/**
	 * Original signature : <code>int cbGetConfig(int, int, int, int, int*)</code><br>
	 * <i>native declaration : line 1696</i><br>
	 * @deprecated use the safer methods {@link #cbGetConfig(int, int, int, int, java.nio.IntBuffer)} and {@link #cbGetConfig(int, int, int, int, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbGetConfig(int InfoType, int BoardNum, int DevNum, int ConfigItem, IntByReference ConfigVal);
	/**
	 * Original signature : <code>int cbGetConfig(int, int, int, int, int*)</code><br>
	 * <i>native declaration : line 1696</i>
	 */
	public static native int cbGetConfig(int InfoType, int BoardNum, int DevNum, int ConfigItem, IntBuffer ConfigVal);
	/**
	 * Original signature : <code>int cbGetConfigString(int, int, int, int, char*, int*)</code><br>
	 * <i>native declaration : line 1698</i><br>
	 * @deprecated use the safer methods {@link #cbGetConfigString(int, int, int, int, java.lang.String, java.nio.IntBuffer)} and {@link #cbGetConfigString(int, int, int, int, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbGetConfigString(int InfoType, int BoardNum, int DevNum, int ConfigItem, Pointer ConfigVal, IntByReference maxConfigLen);
	/**
	 * Original signature : <code>int cbGetConfigString(int, int, int, int, char*, int*)</code><br>
	 * <i>native declaration : line 1698</i>
	 */
	public static native int cbGetConfigString(int InfoType, int BoardNum, int DevNum, int ConfigItem, String ConfigVal, IntBuffer maxConfigLen);
	/**
	 * Original signature : <code>int cbSetConfig(int, int, int, int, int)</code><br>
	 * <i>native declaration : line 1701</i>
	 */
	public static native int cbSetConfig(int InfoType, int BoardNum, int DevNum, int ConfigItem, int ConfigVal);
	/**
	 * Original signature : <code>int cbSetConfigString(int, int, int, int, char*, int*)</code><br>
	 * <i>native declaration : line 1703</i><br>
	 * @deprecated use the safer methods {@link #cbSetConfigString(int, int, int, int, java.lang.String, java.nio.IntBuffer)} and {@link #cbSetConfigString(int, int, int, int, com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbSetConfigString(int InfoType, int BoardNum, int DevNum, int ConfigItem, Pointer ConfigVal, IntByReference configLen);
	/**
	 * Original signature : <code>int cbSetConfigString(int, int, int, int, char*, int*)</code><br>
	 * <i>native declaration : line 1703</i>
	 */
	public static native int cbSetConfigString(int InfoType, int BoardNum, int DevNum, int ConfigItem, String ConfigVal, IntBuffer configLen);
	/**
	 * Original signature : <code>int cbToEngUnits(int, int, USHORT, float*)</code><br>
	 * <i>native declaration : line 1706</i><br>
	 * @deprecated use the safer methods {@link #cbToEngUnits(int, int, short, java.nio.FloatBuffer)} and {@link #cbToEngUnits(int, int, short, com.sun.jna.ptr.FloatByReference)} instead
	 */
	@Deprecated 
	public static native int cbToEngUnits(int BoardNum, int Range, short DataVal, FloatByReference EngUnits);
	/**
	 * Original signature : <code>int cbToEngUnits(int, int, USHORT, float*)</code><br>
	 * <i>native declaration : line 1706</i>
	 */
	public static native int cbToEngUnits(int BoardNum, int Range, short DataVal, FloatBuffer EngUnits);
	/**
	 * Original signature : <code>int cbToEngUnits32(int, int, ULONG, double*)</code><br>
	 * <i>native declaration : line 1708</i><br>
	 * @deprecated use the safer methods {@link #cbToEngUnits32(int, int, com.sun.jna.NativeLong, java.nio.DoubleBuffer)} and {@link #cbToEngUnits32(int, int, com.sun.jna.NativeLong, com.sun.jna.ptr.DoubleByReference)} instead
	 */
	@Deprecated 
	public static native int cbToEngUnits32(int BoardNum, int Range, NativeLong DataVal, DoubleByReference EngUnits);
	/**
	 * Original signature : <code>int cbToEngUnits32(int, int, ULONG, double*)</code><br>
	 * <i>native declaration : line 1708</i>
	 */
	public static native int cbToEngUnits32(int BoardNum, int Range, NativeLong DataVal, DoubleBuffer EngUnits);
	/**
	 * Original signature : <code>int cbFromEngUnits(int, int, float, USHORT*)</code><br>
	 * <i>native declaration : line 1710</i><br>
	 * @deprecated use the safer methods {@link #cbFromEngUnits(int, int, float, java.nio.ShortBuffer)} and {@link #cbFromEngUnits(int, int, float, com.sun.jna.ptr.ShortByReference)} instead
	 */
	@Deprecated 
	public static native int cbFromEngUnits(int BoardNum, int Range, float EngUnits, ShortByReference DataVal);
	/**
	 * Original signature : <code>int cbFromEngUnits(int, int, float, USHORT*)</code><br>
	 * <i>native declaration : line 1710</i>
	 */
	public static native int cbFromEngUnits(int BoardNum, int Range, float EngUnits, ShortBuffer DataVal);
	/**
	 * Original signature : <code>int cbGetBoardName(int, char*)</code><br>
	 * <i>native declaration : line 1712</i><br>
	 * @deprecated use the safer methods {@link #cbGetBoardName(int, java.lang.String)} and {@link #cbGetBoardName(int, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	public static native int cbGetBoardName(int BoardNum, Pointer BoardName);
	/**
	 * Original signature : <code>int cbGetBoardName(int, char*)</code><br>
	 * <i>native declaration : line 1712</i>
	 */
	public static native int cbGetBoardName(int BoardNum, String BoardName);
	/**
	 * Original signature : <code>int cbDeclareRevision(float*)</code><br>
	 * <i>native declaration : line 1713</i><br>
	 * @deprecated use the safer methods {@link #cbDeclareRevision(java.nio.FloatBuffer)} and {@link #cbDeclareRevision(com.sun.jna.ptr.FloatByReference)} instead
	 */
	@Deprecated 
	public static native int cbDeclareRevision(FloatByReference RevNum);
	/**
	 * Original signature : <code>int cbDeclareRevision(float*)</code><br>
	 * <i>native declaration : line 1713</i>
	 */
	public static native int cbDeclareRevision(FloatBuffer RevNum);
	/**
	 * Original signature : <code>int cbSetTrigger(int, int, USHORT, USHORT)</code><br>
	 * <i>native declaration : line 1714</i>
	 */
	public static native int cbSetTrigger(int BoardNum, int TrigType, short LowThreshold, short HighThreshold);
	/**
	 * Original signature : <code>int cbEnableEvent(int, unsigned, unsigned, EVENTCALLBACK, void*)</code><br>
	 * <i>native declaration : line 1717</i>
	 */
	public static native int cbEnableEvent(int BoardNum, int EventType, int Count, MccUniversalLibraryLibrary.EVENTCALLBACK CallbackFunc, Pointer UserData);
	/**
	 * Original signature : <code>int cbDisableEvent(int, unsigned)</code><br>
	 * <i>native declaration : line 1720</i>
	 */
	public static native int cbDisableEvent(int BoardNum, int EventType);
	/**
	 * Original signature : <code>int cbSelectSignal(int, int, int, int, int)</code><br>
	 * <i>native declaration : line 1721</i>
	 */
	public static native int cbSelectSignal(int BoardNum, int Direction, int Signal, int Connection, int Polarity);
	/**
	 * Original signature : <code>int cbGetSignal(int, int, int, int, int*, int*)</code><br>
	 * <i>native declaration : line 1722</i><br>
	 * @deprecated use the safer methods {@link #cbGetSignal(int, int, int, int, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #cbGetSignal(int, int, int, int, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbGetSignal(int BoardNum, int Direction, int Signal, int Index, IntByReference Connection, IntByReference Polarity);
	/**
	 * Original signature : <code>int cbGetSignal(int, int, int, int, int*, int*)</code><br>
	 * <i>native declaration : line 1722</i>
	 */
	public static native int cbGetSignal(int BoardNum, int Direction, int Signal, int Index, IntBuffer Connection, IntBuffer Polarity);
	/**
	 * Original signature : <code>int cbSetCalCoeff(int, int, int, int, int, int, int)</code><br>
	 * <i>native declaration : line 1724</i>
	 */
	public static native int cbSetCalCoeff(int BoardNum, int FunctionType, int Channel, int Range, int Item, int Value, int Store);
	/**
	 * Original signature : <code>int cbGetCalCoeff(int, int, int, int, int, int*)</code><br>
	 * <i>native declaration : line 1725</i><br>
	 * @deprecated use the safer methods {@link #cbGetCalCoeff(int, int, int, int, int, java.nio.IntBuffer)} and {@link #cbGetCalCoeff(int, int, int, int, int, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbGetCalCoeff(int BoardNum, int FunctionType, int Channel, int Range, int Item, IntByReference Value);
	/**
	 * Original signature : <code>int cbGetCalCoeff(int, int, int, int, int, int*)</code><br>
	 * <i>native declaration : line 1725</i>
	 */
	public static native int cbGetCalCoeff(int BoardNum, int FunctionType, int Channel, int Range, int Item, IntBuffer Value);
	/**
	 * store the preferences<br>
	 * Original signature : <code>int cbLogSetPreferences(int, int, int)</code><br>
	 * <i>native declaration : line 1731</i>
	 */
	public static native int cbLogSetPreferences(int timeFormat, int timeZone, int units);
	/**
	 * get the preferences<br>
	 * Original signature : <code>int cbLogGetPreferences(int*, int*, int*)</code><br>
	 * <i>native declaration : line 1734</i><br>
	 * @deprecated use the safer methods {@link #cbLogGetPreferences(java.nio.IntBuffer, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #cbLogGetPreferences(com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbLogGetPreferences(IntByReference timeFormat, IntByReference timeZone, IntByReference units);
	/**
	 * get the preferences<br>
	 * Original signature : <code>int cbLogGetPreferences(int*, int*, int*)</code><br>
	 * <i>native declaration : line 1734</i>
	 */
	public static native int cbLogGetPreferences(IntBuffer timeFormat, IntBuffer timeZone, IntBuffer units);
	/**
	 * Get log file name<br>
	 * Original signature : <code>int cbLogGetFileName(int, char*, char*)</code><br>
	 * <i>native declaration : line 1737</i><br>
	 * @deprecated use the safer methods {@link #cbLogGetFileName(int, java.lang.String, java.lang.String)} and {@link #cbLogGetFileName(int, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	public static native int cbLogGetFileName(int fileNumber, Pointer path, Pointer filename);
	/**
	 * Get log file name<br>
	 * Original signature : <code>int cbLogGetFileName(int, char*, char*)</code><br>
	 * <i>native declaration : line 1737</i>
	 */
	public static native int cbLogGetFileName(int fileNumber, String path, String filename);
	/**
	 * Get info for log file<br>
	 * Original signature : <code>int cbLogGetFileInfo(char*, int*, int*)</code><br>
	 * <i>native declaration : line 1740</i><br>
	 * @deprecated use the safer methods {@link #cbLogGetFileInfo(java.lang.String, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #cbLogGetFileInfo(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbLogGetFileInfo(Pointer filename, IntByReference version, IntByReference fileSize);
	/**
	 * Get info for log file<br>
	 * Original signature : <code>int cbLogGetFileInfo(char*, int*, int*)</code><br>
	 * <i>native declaration : line 1740</i>
	 */
	public static native int cbLogGetFileInfo(String filename, IntBuffer version, IntBuffer fileSize);
	/**
	 * Get sample info for log file<br>
	 * Original signature : <code>int cbLogGetSampleInfo(char*, int*, int*, int*, int*)</code><br>
	 * <i>native declaration : line 1743</i><br>
	 * @deprecated use the safer methods {@link #cbLogGetSampleInfo(java.lang.String, java.nio.IntBuffer, java.nio.IntBuffer, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #cbLogGetSampleInfo(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbLogGetSampleInfo(Pointer filename, IntByReference sampleInterval, IntByReference sampleCount, IntByReference startDate, IntByReference startTime);
	/**
	 * Get sample info for log file<br>
	 * Original signature : <code>int cbLogGetSampleInfo(char*, int*, int*, int*, int*)</code><br>
	 * <i>native declaration : line 1743</i>
	 */
	public static native int cbLogGetSampleInfo(String filename, IntBuffer sampleInterval, IntBuffer sampleCount, IntBuffer startDate, IntBuffer startTime);
	/**
	 * Get the AI channel count for log file<br>
	 * Original signature : <code>int cbLogGetAIChannelCount(char*, int*)</code><br>
	 * <i>native declaration : line 1747</i><br>
	 * @deprecated use the safer methods {@link #cbLogGetAIChannelCount(java.lang.String, java.nio.IntBuffer)} and {@link #cbLogGetAIChannelCount(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbLogGetAIChannelCount(Pointer filename, IntByReference aiCount);
	/**
	 * Get the AI channel count for log file<br>
	 * Original signature : <code>int cbLogGetAIChannelCount(char*, int*)</code><br>
	 * <i>native declaration : line 1747</i>
	 */
	public static native int cbLogGetAIChannelCount(String filename, IntBuffer aiCount);
	/**
	 * Get AI info for log file<br>
	 * Original signature : <code>int cbLogGetAIInfo(char*, int*, int*)</code><br>
	 * <i>native declaration : line 1750</i><br>
	 * @deprecated use the safer methods {@link #cbLogGetAIInfo(java.lang.String, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #cbLogGetAIInfo(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbLogGetAIInfo(Pointer filename, IntByReference channelNumbers, IntByReference units);
	/**
	 * Get AI info for log file<br>
	 * Original signature : <code>int cbLogGetAIInfo(char*, int*, int*)</code><br>
	 * <i>native declaration : line 1750</i>
	 */
	public static native int cbLogGetAIInfo(String filename, IntBuffer channelNumbers, IntBuffer units);
	/**
	 * Get CJC info for log file<br>
	 * Original signature : <code>int cbLogGetCJCInfo(char*, int*)</code><br>
	 * <i>native declaration : line 1753</i><br>
	 * @deprecated use the safer methods {@link #cbLogGetCJCInfo(java.lang.String, java.nio.IntBuffer)} and {@link #cbLogGetCJCInfo(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbLogGetCJCInfo(Pointer filename, IntByReference cjcCount);
	/**
	 * Get CJC info for log file<br>
	 * Original signature : <code>int cbLogGetCJCInfo(char*, int*)</code><br>
	 * <i>native declaration : line 1753</i>
	 */
	public static native int cbLogGetCJCInfo(String filename, IntBuffer cjcCount);
	/**
	 * Get DIO info for log file<br>
	 * Original signature : <code>int cbLogGetDIOInfo(char*, int*)</code><br>
	 * <i>native declaration : line 1756</i><br>
	 * @deprecated use the safer methods {@link #cbLogGetDIOInfo(java.lang.String, java.nio.IntBuffer)} and {@link #cbLogGetDIOInfo(com.sun.jna.Pointer, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbLogGetDIOInfo(Pointer filename, IntByReference dioCount);
	/**
	 * Get DIO info for log file<br>
	 * Original signature : <code>int cbLogGetDIOInfo(char*, int*)</code><br>
	 * <i>native declaration : line 1756</i>
	 */
	public static native int cbLogGetDIOInfo(String filename, IntBuffer dioCount);
	/**
	 * read the time tags to an array<br>
	 * Original signature : <code>int cbLogReadTimeTags(char*, int, int, int*, int*)</code><br>
	 * <i>native declaration : line 1759</i><br>
	 * @deprecated use the safer methods {@link #cbLogReadTimeTags(java.lang.String, int, int, java.nio.IntBuffer, java.nio.IntBuffer)} and {@link #cbLogReadTimeTags(com.sun.jna.Pointer, int, int, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbLogReadTimeTags(Pointer filename, int startSample, int count, IntByReference dateTags, IntByReference timeTags);
	/**
	 * read the time tags to an array<br>
	 * Original signature : <code>int cbLogReadTimeTags(char*, int, int, int*, int*)</code><br>
	 * <i>native declaration : line 1759</i>
	 */
	public static native int cbLogReadTimeTags(String filename, int startSample, int count, IntBuffer dateTags, IntBuffer timeTags);
	/**
	 * read the analog data to an array<br>
	 * Original signature : <code>int cbLogReadAIChannels(char*, int, int, float*)</code><br>
	 * <i>native declaration : line 1762</i><br>
	 * @deprecated use the safer methods {@link #cbLogReadAIChannels(java.lang.String, int, int, java.nio.FloatBuffer)} and {@link #cbLogReadAIChannels(com.sun.jna.Pointer, int, int, com.sun.jna.ptr.FloatByReference)} instead
	 */
	@Deprecated 
	public static native int cbLogReadAIChannels(Pointer filename, int startSample, int count, FloatByReference analog);
	/**
	 * read the analog data to an array<br>
	 * Original signature : <code>int cbLogReadAIChannels(char*, int, int, float*)</code><br>
	 * <i>native declaration : line 1762</i>
	 */
	public static native int cbLogReadAIChannels(String filename, int startSample, int count, FloatBuffer analog);
	/**
	 * read the CJC data to an array<br>
	 * Original signature : <code>int cbLogReadCJCChannels(char*, int, int, float*)</code><br>
	 * <i>native declaration : line 1765</i><br>
	 * @deprecated use the safer methods {@link #cbLogReadCJCChannels(java.lang.String, int, int, java.nio.FloatBuffer)} and {@link #cbLogReadCJCChannels(com.sun.jna.Pointer, int, int, com.sun.jna.ptr.FloatByReference)} instead
	 */
	@Deprecated 
	public static native int cbLogReadCJCChannels(Pointer filename, int startSample, int count, FloatByReference cjc);
	/**
	 * read the CJC data to an array<br>
	 * Original signature : <code>int cbLogReadCJCChannels(char*, int, int, float*)</code><br>
	 * <i>native declaration : line 1765</i>
	 */
	public static native int cbLogReadCJCChannels(String filename, int startSample, int count, FloatBuffer cjc);
	/**
	 * read the DIO data to an array<br>
	 * Original signature : <code>int cbLogReadDIOChannels(char*, int, int, int*)</code><br>
	 * <i>native declaration : line 1768</i><br>
	 * @deprecated use the safer methods {@link #cbLogReadDIOChannels(java.lang.String, int, int, java.nio.IntBuffer)} and {@link #cbLogReadDIOChannels(com.sun.jna.Pointer, int, int, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbLogReadDIOChannels(Pointer filename, int startSample, int count, IntByReference dio);
	/**
	 * read the DIO data to an array<br>
	 * Original signature : <code>int cbLogReadDIOChannels(char*, int, int, int*)</code><br>
	 * <i>native declaration : line 1768</i>
	 */
	public static native int cbLogReadDIOChannels(String filename, int startSample, int count, IntBuffer dio);
	/**
	 * convert the log file to a .TXT or .CSV file<br>
	 * Original signature : <code>int cbLogConvertFile(char*, char*, int, int, int)</code><br>
	 * <i>native declaration : line 1771</i><br>
	 * @deprecated use the safer methods {@link #cbLogConvertFile(java.lang.String, java.lang.String, int, int, int)} and {@link #cbLogConvertFile(com.sun.jna.Pointer, com.sun.jna.Pointer, int, int, int)} instead
	 */
	@Deprecated 
	public static native int cbLogConvertFile(Pointer srcFilename, Pointer destFilename, int startSample, int count, int delimiter);
	/**
	 * convert the log file to a .TXT or .CSV file<br>
	 * Original signature : <code>int cbLogConvertFile(char*, char*, int, int, int)</code><br>
	 * <i>native declaration : line 1771</i>
	 */
	public static native int cbLogConvertFile(String srcFilename, String destFilename, int startSample, int count, int delimiter);
	/**
	 * Original signature : <code>int cbDaqInScan(int, short*, short*, short*, int, long*, long*, long*, HGLOBAL, int)</code><br>
	 * <i>native declaration : line 1773</i><br>
	 * @deprecated use the safer methods {@link #cbDaqInScan(int, java.nio.ShortBuffer, java.nio.ShortBuffer, java.nio.ShortBuffer, int, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.NativeLongByReference, mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, int)} and {@link #cbDaqInScan(int, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.ShortByReference, int, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.ptr.NativeLongByReference, mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, int)} instead
	 */
	@Deprecated 
	public static native int cbDaqInScan(int BoardNum, ShortByReference ChanArray, ShortByReference ChanTypeArray, ShortByReference GainArray, int ChanCount, NativeLongByReference Rate, NativeLongByReference PretrigCount, NativeLongByReference TotalCount, MccUniversalLibraryLibrary.HGLOBAL MemHandle, int Options);
	/**
	 * Original signature : <code>int cbDaqInScan(int, short*, short*, short*, int, long*, long*, long*, HGLOBAL, int)</code><br>
	 * <i>native declaration : line 1773</i>
	 */
	public static native int cbDaqInScan(int BoardNum, ShortBuffer ChanArray, ShortBuffer ChanTypeArray, ShortBuffer GainArray, int ChanCount, NativeLongByReference Rate, NativeLongByReference PretrigCount, NativeLongByReference TotalCount, MccUniversalLibraryLibrary.HGLOBAL MemHandle, int Options);
	/**
	 * Original signature : <code>int cbDaqSetTrigger(int, int, int, int, int, int, float, float, int)</code><br>
	 * <i>native declaration : line 1775</i>
	 */
	public static native int cbDaqSetTrigger(int BoardNum, int TrigSource, int TrigSense, int TrigChan, int ChanType, int Gain, float Level, float Variance, int TrigEvent);
	/**
	 * Original signature : <code>int cbDaqSetSetpoints(int, float*, float*, float*, int*, int*, float*, float*, float*, float*, int)</code><br>
	 * <i>native declaration : line 1777</i><br>
	 * @deprecated use the safer methods {@link #cbDaqSetSetpoints(int, java.nio.FloatBuffer, java.nio.FloatBuffer, java.nio.FloatBuffer, java.nio.IntBuffer, java.nio.IntBuffer, java.nio.FloatBuffer, java.nio.FloatBuffer, java.nio.FloatBuffer, java.nio.FloatBuffer, int)} and {@link #cbDaqSetSetpoints(int, com.sun.jna.ptr.FloatByReference, com.sun.jna.ptr.FloatByReference, com.sun.jna.ptr.FloatByReference, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.IntByReference, com.sun.jna.ptr.FloatByReference, com.sun.jna.ptr.FloatByReference, com.sun.jna.ptr.FloatByReference, com.sun.jna.ptr.FloatByReference, int)} instead
	 */
	@Deprecated 
	public static native int cbDaqSetSetpoints(int BoardNum, FloatByReference LimitAArray, FloatByReference LimitBArray, FloatByReference Reserved, IntByReference SetpointFlagsArray, IntByReference SetpointOutputArray, FloatByReference Output1Array, FloatByReference Output2Array, FloatByReference OutputMask1Array, FloatByReference OutputMask2Array, int SetpointCount);
	/**
	 * Original signature : <code>int cbDaqSetSetpoints(int, float*, float*, float*, int*, int*, float*, float*, float*, float*, int)</code><br>
	 * <i>native declaration : line 1777</i>
	 */
	public static native int cbDaqSetSetpoints(int BoardNum, FloatBuffer LimitAArray, FloatBuffer LimitBArray, FloatBuffer Reserved, IntBuffer SetpointFlagsArray, IntBuffer SetpointOutputArray, FloatBuffer Output1Array, FloatBuffer Output2Array, FloatBuffer OutputMask1Array, FloatBuffer OutputMask2Array, int SetpointCount);
	/**
	 * Original signature : <code>int cbDaqOutScan(int, short*, short*, short*, int, long*, long, HGLOBAL, int)</code><br>
	 * <i>native declaration : line 1781</i><br>
	 * @deprecated use the safer methods {@link #cbDaqOutScan(int, java.nio.ShortBuffer, java.nio.ShortBuffer, java.nio.ShortBuffer, int, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.NativeLong, mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, int)} and {@link #cbDaqOutScan(int, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.ShortByReference, int, com.sun.jna.ptr.NativeLongByReference, com.sun.jna.NativeLong, mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, int)} instead
	 */
	@Deprecated 
	public static native int cbDaqOutScan(int BoardNum, ShortByReference ChanArray, ShortByReference ChanTypeArray, ShortByReference GainArray, int ChanCount, NativeLongByReference Rate, NativeLong Count, MccUniversalLibraryLibrary.HGLOBAL MemHandle, int Options);
	/**
	 * Original signature : <code>int cbDaqOutScan(int, short*, short*, short*, int, long*, long, HGLOBAL, int)</code><br>
	 * <i>native declaration : line 1781</i>
	 */
	public static native int cbDaqOutScan(int BoardNum, ShortBuffer ChanArray, ShortBuffer ChanTypeArray, ShortBuffer GainArray, int ChanCount, NativeLongByReference Rate, NativeLong Count, MccUniversalLibraryLibrary.HGLOBAL MemHandle, int Options);
	/**
	 * Original signature : <code>int cbGetTCValues(int, short*, short*, int, HGLOBAL, int, long, int, float*)</code><br>
	 * <i>native declaration : line 1783</i><br>
	 * @deprecated use the safer methods {@link #cbGetTCValues(int, java.nio.ShortBuffer, java.nio.ShortBuffer, int, mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, int, com.sun.jna.NativeLong, int, java.nio.FloatBuffer)} and {@link #cbGetTCValues(int, com.sun.jna.ptr.ShortByReference, com.sun.jna.ptr.ShortByReference, int, mccuniversallibrary.MccUniversalLibraryLibrary.HGLOBAL, int, com.sun.jna.NativeLong, int, com.sun.jna.ptr.FloatByReference)} instead
	 */
	@Deprecated 
	public static native int cbGetTCValues(int BoardNum, ShortByReference ChanArray, ShortByReference ChanTypeArray, int ChanCount, MccUniversalLibraryLibrary.HGLOBAL MemHandle, int FirstPoint, NativeLong Count, int Scale, FloatByReference TempValArray);
	/**
	 * Original signature : <code>int cbGetTCValues(int, short*, short*, int, HGLOBAL, int, long, int, float*)</code><br>
	 * <i>native declaration : line 1783</i>
	 */
	public static native int cbGetTCValues(int BoardNum, ShortBuffer ChanArray, ShortBuffer ChanTypeArray, int ChanCount, MccUniversalLibraryLibrary.HGLOBAL MemHandle, int FirstPoint, NativeLong Count, int Scale, FloatBuffer TempValArray);
	/**
	 * Original signature : <code>int cbVIn(int, int, int, float*, int)</code><br>
	 * <i>native declaration : line 1786</i><br>
	 * @deprecated use the safer methods {@link #cbVIn(int, int, int, java.nio.FloatBuffer, int)} and {@link #cbVIn(int, int, int, com.sun.jna.ptr.FloatByReference, int)} instead
	 */
	@Deprecated 
	public static native int cbVIn(int BoardNum, int Chan, int Gain, FloatByReference DataValue, int Options);
	/**
	 * Original signature : <code>int cbVIn(int, int, int, float*, int)</code><br>
	 * <i>native declaration : line 1786</i>
	 */
	public static native int cbVIn(int BoardNum, int Chan, int Gain, FloatBuffer DataValue, int Options);
	/**
	 * Original signature : <code>int cbVIn32(int, int, int, double*, int)</code><br>
	 * <i>native declaration : line 1787</i><br>
	 * @deprecated use the safer methods {@link #cbVIn32(int, int, int, java.nio.DoubleBuffer, int)} and {@link #cbVIn32(int, int, int, com.sun.jna.ptr.DoubleByReference, int)} instead
	 */
	@Deprecated 
	public static native int cbVIn32(int BoardNum, int Chan, int Gain, DoubleByReference DataValue, int Options);
	/**
	 * Original signature : <code>int cbVIn32(int, int, int, double*, int)</code><br>
	 * <i>native declaration : line 1787</i>
	 */
	public static native int cbVIn32(int BoardNum, int Chan, int Gain, DoubleBuffer DataValue, int Options);
	/**
	 * Original signature : <code>int cbVOut(int, int, int, float, int)</code><br>
	 * <i>native declaration : line 1788</i>
	 */
	public static native int cbVOut(int BoardNum, int Chan, int Gain, float DataValue, int Options);
	/**
	 * Original signature : <code>int cbDeviceLogin(int, char*, char*)</code><br>
	 * <i>native declaration : line 1790</i><br>
	 * @deprecated use the safer methods {@link #cbDeviceLogin(int, java.lang.String, java.lang.String)} and {@link #cbDeviceLogin(int, com.sun.jna.Pointer, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	public static native int cbDeviceLogin(int BoardNum, Pointer AccountName, Pointer Password);
	/**
	 * Original signature : <code>int cbDeviceLogin(int, char*, char*)</code><br>
	 * <i>native declaration : line 1790</i>
	 */
	public static native int cbDeviceLogin(int BoardNum, String AccountName, String Password);
	/**
	 * Original signature : <code>int cbDeviceLogout(int)</code><br>
	 * <i>native declaration : line 1791</i>
	 */
	public static native int cbDeviceLogout(int BoardNum);
	/**
	 * Original signature : <code>int cbTEDSRead(int, int, BYTE*, long*, int)</code><br>
	 * <i>native declaration : line 1793</i><br>
	 * @deprecated use the safer methods {@link #cbTEDSRead(int, int, java.nio.ByteBuffer, com.sun.jna.ptr.NativeLongByReference, int)} and {@link #cbTEDSRead(int, int, com.sun.jna.Pointer, com.sun.jna.ptr.NativeLongByReference, int)} instead
	 */
	@Deprecated 
	public static native int cbTEDSRead(int BoardNum, int Chan, Pointer DataBuffer, NativeLongByReference Count, int Options);
	/**
	 * Original signature : <code>int cbTEDSRead(int, int, BYTE*, long*, int)</code><br>
	 * <i>native declaration : line 1793</i>
	 */
	public static native int cbTEDSRead(int BoardNum, int Chan, ByteBuffer DataBuffer, NativeLongByReference Count, int Options);
	/**
	 * Original signature : <code>int cbAInputMode(int, int)</code><br>
	 * <i>native declaration : line 1795</i>
	 */
	public static native int cbAInputMode(int BoardNum, int InputMode);
	/**
	 * Original signature : <code>int cbAChanInputMode(int, int, int)</code><br>
	 * <i>native declaration : line 1796</i>
	 */
	public static native int cbAChanInputMode(int BoardNum, int Chan, int InputMode);
	/**
	 * Original signature : <code>int cbIgnoreInstaCal()</code><br>
	 * <i>native declaration : line 1798</i>
	 */
	public static native int cbIgnoreInstaCal();
	/**
	 * Original signature : <code>int cbCreateDaqDevice(int, DaqDeviceDescriptor)</code><br>
	 * <i>native declaration : line 1799</i>
	 */
	public static native int cbCreateDaqDevice(int BdNum, DaqDeviceDescriptor.ByValue DeviceDescriptor);
	/**
	 * Original signature : <code>int cbGetDaqDeviceInventory(DaqDeviceInterface, DaqDeviceDescriptor*, INT*)</code><br>
	 * <i>native declaration : line 1800</i><br>
	 * @deprecated use the safer methods {@link #cbGetDaqDeviceInventory(int, mccuniversallibrary.DaqDeviceDescriptor, java.nio.IntBuffer)} and {@link #cbGetDaqDeviceInventory(int, mccuniversallibrary.DaqDeviceDescriptor, com.sun.jna.ptr.IntByReference)} instead
	 */
	@Deprecated 
	public static native int cbGetDaqDeviceInventory(int InterfaceType, DaqDeviceDescriptor Inventory, IntByReference NumberOfDevices);
	/**
	 * Original signature : <code>int cbGetDaqDeviceInventory(DaqDeviceInterface, DaqDeviceDescriptor*, INT*)</code><br>
	 * <i>native declaration : line 1800</i>
	 */
	public static native int cbGetDaqDeviceInventory(int InterfaceType, Pointer Inventory, IntBuffer NumberOfDevices);
	/**
	 * Original signature : <code>int cbReleaseDaqDevice(int)</code><br>
	 * <i>native declaration : line 1801</i>
	 */
	public static native int cbReleaseDaqDevice(int BdNum);
	/**
	 * Original signature : <code>int cbGetBoardNumber(DaqDeviceDescriptor)</code><br>
	 * <i>native declaration : line 1802</i>
	 */
	public static native int cbGetBoardNumber(DaqDeviceDescriptor.ByValue DeviceDescriptor);
	/**
	 * Original signature : <code>int cbGetNetDeviceDescriptor(CHAR*, INT, DaqDeviceDescriptor*, INT)</code><br>
	 * <i>native declaration : line 1803</i><br>
	 * @deprecated use the safer methods {@link #cbGetNetDeviceDescriptor(java.nio.ByteBuffer, int, mccuniversallibrary.DaqDeviceDescriptor, int)} and {@link #cbGetNetDeviceDescriptor(com.sun.jna.Pointer, int, mccuniversallibrary.DaqDeviceDescriptor, int)} instead
	 */
	@Deprecated 
	public static native int cbGetNetDeviceDescriptor(Pointer Host, int Port, DaqDeviceDescriptor DeviceDescriptor, int Timeout);
	/**
	 * Original signature : <code>int cbGetNetDeviceDescriptor(CHAR*, INT, DaqDeviceDescriptor*, INT)</code><br>
	 * <i>native declaration : line 1803</i>
	 */
	public static native int cbGetNetDeviceDescriptor(ByteBuffer Host, int Port, DaqDeviceDescriptor DeviceDescriptor, int Timeout);
	public static class HGLOBAL extends PointerType {
		public HGLOBAL(Pointer address) {
			super(address);
		}
		public HGLOBAL() {
			super();
		}
	}
}
